name: Release
run-name: Release ${{ github.ref_name }} 🚀

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test-job.yml
    with:
      ref: ${{ github.ref_name }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: install dependencies
        run: go mod download
      - name: release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
