name: "Unit and Integration"

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: 'Branch or tag'
        required: true
        default: 'main'

env:
  POSTGRESQL_VERSION: 16
  POSTGRESQL_IMAGE: bitnami/postgresql
  TMDB_PG_PORT: 54320
  TMDB_PG_DATABASE: app
  TMDB_PG_USER: app
  TMDB_PG_PASSWORD: app
  TMDB_PG_CONTAINER_NAME: tmdb-pg
  MYSQL_IMAGE: mysql
  MYSQL_VERSION: 8.0
  TMDB_MYSQL_PORT: 33060
  TMDB_MYSQL_DATABASE: app
  TMDB_MYSQL_USER: app
  TMDB_MYSQL_PASSWORD: app
  TMDB_MYSQL_ROOT_PASSWORD: root
  TMDB_MYSQL_CONTAINER_NAME: tmdb-mysql

jobs:
  test:
    name: "Unit and Integration"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - id: setup-go
        name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - id: install-dependencies
        name: install dependencies
        run: go mod download
#      - id: image-cache-setup
#        name: service container cache setup
#        uses: actions/cache@v3
#        with:
#          path: /tmp/image-cache
#          key: test-${{ runner.os }}-image-cache
#      - id: image-cache
#        name: service container cache
#        if: steps.image-cache-setup.outputs.cache-hit != 'true'
#        run: |
#          docker pull ${{ env.POSTGRESQL_IMAGE }}:${{ env.POSTGRESQL_VERSION }};
#
#          docker pull ${{ env.MYSQL_IMAGE }}:${{ env.MYSQL_VERSION }};
#
#          mkdir -p /tmp/image-cache;
#
#          docker save ${{ env.POSTGRESQL_IMAGE }}:${{ env.POSTGRESQL_VERSION }} > /tmp/image-cache/postgresql.tar;
#
#          docker save ${{ env.MYSQL_IMAGE }}:${{ env.MYSQL_VERSION }} > /tmp/image-cache/mysql.tar;
#      - id: image-cache-restore
#        name: service container cache restore
#        if: steps.image-cache-setup.outputs.cache-hit == 'true'
#        run: |
#          docker load -i /tmp/image-cache/postgresql.tar;
#
#          docker load -i /tmp/image-cache/mysql.tar;
      - id: boot-service-containers
        name: boot service containers
        run: |
          docker run -d --name ${{ env.TMDB_PG_CONTAINER_NAME }} \
            -v ./fixtures/pg/seed.sh:/docker-entrypoint-initdb.d/seed.sh \
            -v ./fixtures/pg/01.features.sql:/tmp/01.features.sql \
            -v ./fixtures/pg/02.schema.sql:/tmp/02.schema.sql \
            -v ./fixtures/pg/03.data.sql:/tmp/03.data.sql \
            -p ${{ env.TMDB_PG_PORT }}:5432 \
            -e POSTGRESQL_POSTGRES_PASSWORD=postgres \
            -e POSTGRESQL_DATABASE=${{ env.TMDB_PG_DATABASE }} \
            -e POSTGRESQL_USERNAME=${{ env.TMDB_PG_USER }} \
            -e POSTGRESQL_PASSWORD=${{ env.TMDB_PG_PASSWORD }} \
            ${{ env.POSTGRESQL_IMAGE }}:${{ env.POSTGRESQL_VERSION }};

          docker run -d --name ${{ env.TMDB_MYSQL_CONTAINER_NAME }} \
            -v ./fixtures/mysql/backup.sql:/docker-entrypoint-initdb.d/backup.sql \
            -p ${{ env.TMDB_MYSQL_PORT }}:3306 \
            -e MYSQL_ROOT_PASSWORD=${{ env.TMDB_MYSQL_ROOT_PASSWORD }} \
            -e MYSQL_DATABASE=${{ env.TMDB_MYSQL_DATABASE }} \
            -e MYSQL_USER=${{ env.TMDB_MYSQL_USER }} \
            -e MYSQL_PASSWORD=${{ env.TMDB_MYSQL_PASSWORD }} \
            ${{ env.MYSQL_IMAGE }}:${{ env.MYSQL_VERSION }};
      - id: test
        name: run tests
        env:
          TMDB_PG_PORT: ${{ env.TMDB_PG_PORT }}
          TMDB_PG_DATABASE: ${{ env.TMDB_PG_DATABASE }}
          TMDB_PG_USER: ${{ env.TMDB_PG_USER }}
          TMDB_PG_PASSWORD: ${{ env.TMDB_PG_PASSWORD }}
          TMDB_MYSQL_PORT: ${{ env.TMDB_MYSQL_PORT }}
          TMDB_MYSQL_DATABASE: ${{ env.TMDB_MYSQL_DATABASE }}
          TMDB_MYSQL_USER: ${{ env.TMDB_MYSQL_USER }}
          TMDB_MYSQL_PASSWORD: ${{ env.TMDB_MYSQL_PASSWORD }}
        run: |
          docker inspect ${{ env.TMDB_PG_CONTAINER_NAME }} --format='{{.Name}}: {{.State.Status}}';

          docker inspect ${{ env.TMDB_MYSQL_CONTAINER_NAME }} --format='{{.Name}}: {{.State.Status}}';

          go test -json ./internal/... ./integration/... 2>&1 | tee TestResults.json
      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.json
